[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
evm_version = "paris"
optimizer = true
optimizer_runs = 200  # Para testing
via_ir = false

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fuzz]
runs = 256


